variables:
  TF_VAR_AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  TF_VAR_AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

stages:
  - validate
  - plan
  - deploy

validate:
  stage: validate
  image:
    name: hashicorp/terraform:0.12.7
    entrypoint: [""]
  script:
    - cd src
    - terraform init -input=false
    - terraform validate
  artifacts:
    paths:
      - src/.terraform/

plan:
  stage: plan
  image:
    name: hashicorp/terraform:0.12.7
    entrypoint: [""]
  script:
    - cd src
    - terraform plan -out network-infrastructure.plan
  only:
    - master
  artifacts:
    paths:
      - src/network-infrastructure.plan

deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:0.12.7
    entrypoint: [""]
  script:
    - cd src
    - terraform apply -auto-approve network-infrastructure.plan
  only:
    - master
